version: '3'

vars:
  BUILD_OUT_DIR: './build'
  BUILD_APP_NAME: 'kasinao'

tasks:
  internal-tidy:
    internal: true
    run: once
    cmd: go mod tidy

  internal-build:
    internal: true
    requires:
      vars: [BUILD_OUTPUT]
    env:
      GOOS: "{{.GOOS | default OS}}"
      GOARCH: "{{.GOARCH | default ARCH}}"
    vars:
      BUILD_EXTENSION: '{{if eq .GOOS "windows"}}.exe{{end}}'
    cmds:
      - task: internal-tidy
      - go build -trimpath -o {{ .BUILD_OUTPUT }}{{.BUILD_EXTENSION}}'

  internal-build-os-arch:
    internal: true
    requires:
      vars: [GOOS, GOARCH]
    cmds:
      - task: internal-build
        vars:
          BUILD_OUTPUT: "{{ .BUILD_OUT_DIR }}/{{ .BUILD_APP_NAME }}-{{.GOOS}}-{{.GOARCH}}"
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"

  build-linux-arm64:
    run: once
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "linux"
          GOARCH: "arm64"

  build-linux-amd64:
    run: once
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "linux"
          GOARCH: "amd64"

  build-windows-amd64:
    run: once
    cmds:
      - task: internal-build-os-arch
        vars:
          GOOS: "windows"
          GOARCH: "amd64"

  build-all:
    run: once
    cmds:
      - task: build-linux-arm64
      - task: build-linux-amd64
      - task: build-windows-amd64

  build:
    run: once
    vars:
      BUILD_OUTPUT: "{{ .BUILD_OUT_DIR }}/{{ .BUILD_APP_NAME }}"
    cmds:
      - task: internal-build
        vars:
          BUILD_OUTPUT: "{{.BUILD_OUTPUT}}"

  install:
    run: once
    cmd: go install -trimpath'

  tidy:
    cmd:
      task: internal-tidy